"""Using the skill in someone else's repository: detection, root finding,
protecting a hand-written CHANGELOG.md, and install.sh."""
import json
import os
import subprocess
import tempfile
import unittest

from helpers import ENV, PY, ROOT, git, run

import _common


class ForeignRepo(unittest.TestCase):
    """A repo that has never seen Shiplog: package.json, tags without a 'v'."""

    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.d = os.path.realpath(self.tmp.name)
        git(self.d, "init", "-q", "-b", "main")
        git(self.d, "config", "user.email", "t@t.t")
        git(self.d, "config", "user.name", "T")
        git(self.d, "config", "commit.gpgsign", "false")
        os.makedirs(os.path.join(self.d, "src"))
        self.write("package.json", json.dumps({"name": "@acme/acme-dashboard", "version": "1.4.0",
                                               "description": "Acme analytics dashboard"}))
        self.commit("src/a.js", "initial")
        git(self.d, "tag", "1.4.0")
        self.commit("src/b.js", "feat: add CSV export (#12)")

    def tearDown(self):
        self.tmp.cleanup()

    def write(self, name, text):
        with open(os.path.join(self.d, name), "w") as f:
            f.write(text)

    def commit(self, name, msg):
        self.write(name, msg)
        git(self.d, "add", ".")
        git(self.d, "commit", "-qm", msg)

    def shiplog(self, *args, cwd=None):
        return run("shiplog.py", *args, cwd=cwd or self.d)

    def config(self):
        with open(os.path.join(self.d, ".shiplog.json")) as f:
            return json.load(f)["apps"][0]

    def test_init_from_a_subfolder_detects_everything(self):
        r = self.shiplog("init", cwd=os.path.join(self.d, "src"))
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertFalse(os.path.exists(os.path.join(self.d, "src", ".shiplog.json")))
        app = self.config()
        self.assertEqual((app["id"], app["name"], app["tag_prefix"]), ("acme-dashboard", "Acme Dashboard", ""))
        self.assertEqual(app["description"], "Acme analytics dashboard")

        out = json.loads(self.shiplog("collect", "--full", cwd=os.path.join(self.d, "src")).stdout)
        self.assertEqual((out["last_tag"], out["suggested_version"]), ("1.4.0", "1.5.0"))

    def test_wrong_prefix_is_pointed_out(self):
        self.shiplog("init", "--tag-prefix", "v")
        out = json.loads(self.shiplog("collect", "--full").stdout)
        self.assertTrue(any("tags like '1.4.0'" in n and '"tag_prefix": ""' in n for n in out["notes"]), out["notes"])

    def test_feature_branch_note_and_since(self):
        self.shiplog("init")
        git(self.d, "checkout", "-qb", "8.2")  # release branches are fine
        out = json.loads(self.shiplog("collect", "--full").stdout)
        self.assertFalse(any("branch" in n for n in out["notes"]))
        git(self.d, "checkout", "-qb", "my-feature")
        out = json.loads(self.shiplog("collect", "--full").stdout)
        self.assertTrue(any("branch 'my-feature'" in n for n in out["notes"]))
        out = json.loads(self.shiplog("collect", "--full", "--to", "main").stdout)
        self.assertFalse(any("branch" in n for n in out["notes"]))
        out = json.loads(self.shiplog("collect", "--full", "--to", "main", "--since", "2030-01-01").stdout)
        self.assertEqual(out["change_count"], 0)

    def write_release(self, version="1.5.0"):
        app = self.config()
        rel = {"version": version, "date": "2026-09-28", "entries": [{
            "type": "added", "title": "CSV export", "audiences": ["admins"], "action_required": False,
            "description": "Export any report as a CSV file from the Reports page.", "refs": ["#12"]}]}
        with open(os.path.join(self.d, app["releases_dir"], version + ".json"), "w") as f:
            json.dump(rel, f)

    def test_hand_written_changelog_gets_new_releases_in_its_format(self):
        original = ("# Changelog\n\n## [1.4.0] - 2026-08-01\n### Added\n"
                    "- Hand-written notes the team cares about\n")
        self.write("CHANGELOG.md", original)
        r = self.shiplog("init")
        self.assertIn("adds each new release in the file's own", r.stdout)
        self.write_release()
        r = self.shiplog("release", "--version", "1.5.0")
        self.assertEqual(r.returncode, 0, r.stdout + r.stderr)
        self.assertIn("CHANGELOG.md (added 1.5.0)", r.stdout)
        with open(os.path.join(self.d, "CHANGELOG.md")) as f:
            md = f.read()
        self.assertTrue(md.endswith(original[len("# Changelog\n\n"):]))  # history untouched
        self.assertIn("## [1.5.0] - 2026-09-28\n### Added\n- CSV export\n", md)
        self.assertNotIn("Generated by Shiplog", md)
        self.shiplog("release", "--version", "1.5.0")
        with open(os.path.join(self.d, "CHANGELOG.md")) as f:
            self.assertEqual(f.read(), md)  # idempotent

    def test_regenerate_mode_takes_over_after_import(self):
        self.write("CHANGELOG.md", "# Changelog\n\n## [1.4.0] - 2026-08-01\n### Added\n- Old notes\n")
        self.shiplog("init")
        path = os.path.join(self.d, ".shiplog.json")
        with open(path) as f:
            cfg = json.load(f)
        cfg["apps"][0]["changelog_md_mode"] = "regenerate"
        with open(path, "w") as f:
            json.dump(cfg, f)
        self.write_release()
        r = self.shiplog("release", "--version", "1.5.0")
        self.assertIn("versions without release files (1.4.0)", r.stderr)
        self.shiplog("import")
        self.shiplog("release", "--version", "1.5.0")
        with open(os.path.join(self.d, "CHANGELOG.md")) as f:
            md = f.read()
        self.assertIn("Generated by Shiplog", md)
        self.assertIn("Old notes", md)


class DetectTest(unittest.TestCase):
    def test_manifests(self):
        with tempfile.TemporaryDirectory() as d:
            with open(os.path.join(d, "pyproject.toml"), "w") as f:
                f.write('[build-system]\nrequires = ["x"]\n\n[project]\nname = "travel-kit"\nversion = "2.1.0"\n'
                        'description = "Trips"\n\n[tool.other]\nname = "nope"\n')
            self.assertEqual(_common.detect_project(d), {"name": "travel-kit", "version": "2.1.0",
                                                         "description": "Trips"})
        with tempfile.TemporaryDirectory() as d:
            d = os.path.join(d, "flywheel")
            os.makedirs(d)
            git(d, "init", "-q")
            with open(os.path.join(d, "package.json"), "w") as f:
                json.dump({"name": "web", "version": "0.1.0"}, f)  # starter defaults
            self.assertEqual(_common.detect_project(d), {"name": "flywheel"})

    def test_major_ecosystems(self):
        cases = {
            "go": ({"go.mod": "module github.com/go-chi/chi/v5\n\ngo 1.22\n"}, {"name": "chi"}),
            "maven": ({"pom.xml": "<project><parent><artifactId>oss-parent</artifactId><version>9</version>"
                                  "</parent><artifactId>gson-parent</artifactId><version>2.14.1</version>"
                                  "<name>Gson Parent</name><description>JSON for Java</description></project>"},
                      {"name": "Gson", "description": "JSON for Java", "version": "2.14.1"}),
            "gradle": ({"settings.gradle.kts": 'rootProject.name = "moshi-root"\n',
                        "build.gradle.kts": 'version = "2.0.3"\n'}, {"name": "moshi", "version": "2.0.3"}),
            "dotnet": ({"Polly.csproj": "<Project><PropertyGroup><PackageId>Polly</PackageId>"
                                        "<VersionPrefix>8.8.1</VersionPrefix></PropertyGroup></Project>"},
                       {"name": "Polly", "version": "8.8.1"}),
            "php": ({"composer.json": json.dumps({"name": "guzzlehttp/guzzle", "description": "HTTP client"})},
                    {"name": "guzzle", "description": "HTTP client"}),
            "ruby": ({"sinatra.gemspec": 's.name = "sinatra"\ns.summary = "Classy web-development"\n'},
                     {"name": "sinatra", "description": "Classy web-development"}),
            "rust": ({"Cargo.toml": '[package]\nname = "ripgrep"\nversion = "15.2.1"\n'},
                     {"name": "ripgrep", "version": "15.2.1"}),
        }
        for label, (files, want) in cases.items():
            with self.subTest(label), tempfile.TemporaryDirectory() as d:
                for name, text in files.items():
                    with open(os.path.join(d, name), "w") as f:
                        f.write(text)
                self.assertEqual(_common.detect_project(d), want)

    def test_changelog_file_names(self):
        with tempfile.TemporaryDirectory() as d:
            self.assertIsNone(_common.find_changelog(d))
            for name in ("NEWS", "HISTORY.md"):
                open(os.path.join(d, name), "w").close()
            self.assertEqual(_common.find_changelog(d), "HISTORY.md")

    def test_tag_prefix(self):
        with tempfile.TemporaryDirectory() as d:
            git(d, "init", "-q")
            git(d, "-c", "user.email=t@t.t", "-c", "user.name=T", "commit", "-q", "--allow-empty", "-m", "x")
            self.assertIsNone(_common.detect_tag_prefix(d))
            for t in ("release-1.0.0", "release-1.1.0", "v0.9.0", "nightly"):
                git(d, "tag", t)
            self.assertEqual(_common.detect_tag_prefix(d), "release-")
            # A project that moved from "4.18.2" to "v5.2.1" is read by its current style,
            # and package tags in a monorepo don't outrank the product.
            for t in ("4.17.0", "4.18.0", "4.18.2", "v5.2.1", "ignore-0.4.33"):
                git(d, "tag", t)
            self.assertEqual(_common.detect_tag_prefix(d), "v")


class InstallTest(unittest.TestCase):
    def test_install_into_a_project_and_run(self):
        with tempfile.TemporaryDirectory() as d:
            d = os.path.realpath(d)
            git(d, "init", "-q")
            os.makedirs(os.path.join(d, "sub"))
            r = subprocess.run(["sh", os.path.join(ROOT, "install.sh")], cwd=os.path.join(d, "sub"),
                               capture_output=True, text=True)
            self.assertEqual(r.returncode, 0, r.stderr)
            skill = os.path.join(d, ".claude", "skills", "shiplog")
            self.assertTrue(os.path.exists(os.path.join(skill, "SKILL.md")))
            self.assertFalse(any("__pycache__" in root for root, _, _ in os.walk(skill)))
            r = subprocess.run([PY, os.path.join(skill, "scripts", "shiplog.py"), "init", "--name", "X"],
                               cwd=d, capture_output=True, text=True, env=ENV)
            self.assertEqual(r.returncode, 0, r.stderr)
            self.assertTrue(os.path.exists(os.path.join(d, ".shiplog.json")))


class PythonRequirementTest(unittest.TestCase):
    """Missing or old Python must be reported clearly, never as a confusing error."""

    def fake_path(self, d, python_version=None):
        """A PATH with the tools install.sh needs, plus an optional fake python3."""
        import shutil
        bin_dir = os.path.join(d, "bin")
        os.makedirs(bin_dir)
        for tool in ("sh", "git", "dirname", "cp", "rm", "mkdir", "find", "cat"):
            os.symlink(shutil.which(tool), os.path.join(bin_dir, tool))
        if python_version:
            with open(os.path.join(bin_dir, "python3"), "w") as f:
                f.write('#!/bin/sh\ncase "$*" in *"print"*) echo %s;; *) exit 1;; esac\n' % python_version)
            os.chmod(os.path.join(bin_dir, "python3"), 0o755)
        return bin_dir

    def install(self, path):
        with tempfile.TemporaryDirectory() as repo:
            git(repo, "init", "-q")
            return subprocess.run([self.sh, os.path.join(ROOT, "install.sh")], cwd=repo, capture_output=True,
                                  text=True, env={"PATH": path, "HOME": repo})

    def setUp(self):
        import shutil
        self.sh = shutil.which("sh")

    def test_installer_says_when_python_is_missing(self):
        with tempfile.TemporaryDirectory() as d:
            r = self.install(self.fake_path(d))
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertIn("Shiplog needs Python 3.10 or newer, and none was found", r.stderr)
        self.assertIn("winget install Python.Python.3.12", r.stderr)

    def test_installer_says_when_python_is_too_old(self):
        with tempfile.TemporaryDirectory() as d:
            r = self.install(self.fake_path(d, "3.8"))
        self.assertIn("only found python3 3.8", r.stderr)

    def test_installer_confirms_a_good_python(self):
        r = self.install(os.path.dirname(PY) + os.pathsep + os.environ["PATH"])
        self.assertIn("Found Python", r.stdout)
        self.assertEqual(r.stderr, "")

    def test_scripts_explain_an_old_python(self):
        shim = ("import sys, runpy; sys.version_info = (3, 8, 0, 'final', 0); "
                "sys.argv = [sys.argv[1], 'validate']; runpy.run_path(sys.argv[0], run_name='__main__')")
        r = subprocess.run([PY, "-c", shim, os.path.join(ROOT, "plugins", "shiplog", "skills", "shiplog",
                                                         "scripts", "shiplog.py")], capture_output=True, text=True)
        self.assertEqual(r.returncode, 1)
        self.assertIn("Python 3.10 or newer is required, but this is Python 3.8", r.stderr)


if __name__ == "__main__":
    unittest.main()
